name: Test React App
on: push
jobs:
  test:
    run-on: windows-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v3
      - name: Install dependecies 
        run: npm ci
      - name: Test application
        run: npm run test  